### PR TITLE
feat(led.js):created Led class

### PR DESCRIPTION
**Pull request by EranAvidor**
@udiudi @MeitalT 
please take a look at this architecture
i strongly believe that we should treat resources as classes
the main reason is that we shouldn't have nothing to encapsulate on the server (so private variables are not an issue here) and that we have to keep the instances slim with prototyping.
in addition, i advise to use the sync notation and not to break the library terminology. later we will use both sync and async (probably at the point when we use sockets and live data streams for sensors or such)

please tell me what you think

### CODE REVIEW

**Comment by udiudi** [comment]
A lot better!

**Comment by udiudi** [comment]
How the .prototype. is different from what I did?

**Comment by EranAvidor** [comment]
@udiudi prototyping ~~gets~~ provides you the ability to define class and instance methods (which you can achieve using exports but it's bad practice), it will guide us with better design as the project progresses due to the class responsibility that it reflects 
performance-wise, it means the the methods are defined once per behavior and not per object instance

**Comment by EranAvidor** [comment]
@udiudi this pull request should be merged if we all agree.

**Comment by EranAvidor** [comment]
⭐

**Comment by EranAvidor** [comment]
!ninjastar

**Comment by EranAvidor** [comment]
⭐

**Comment by udiudi** [comment]
!ninjastar

**Pull request merged**
